apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
apiEndpoint:
  advertiseAddress: ${api_advertise_addresses}
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
apiServerCertSANs:
  ${cert_sans}
etcd:
  external:
    endpoints:
    ${etcd_endpoints}
    caFile: ${etcd_ca_certificate}
    certFile: ${etcd_client_certificate}
    keyFile: ${etcd_client_key}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
